# Generated by Django 2.1.15 on 2020-05-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200522_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='images',
        ),
    ]
